project_name: "gssh"
before:
  hooks:
    - "go mod download"
builds:
- env:
  - "CGO_ENABLED=0"
  goos:
  - "linux"
  - "darwin"
  - "windows"
  goarch:
  - "amd64"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: "asc"
  filters:
    exclude:
    - "^docs:"
    - "^test:"
    - "Marge pull request"
    - "Merge branch"
archive:
  replacements:
    darwin: "darwin"
    linux: "linux"
    windows: "windows"
    amd64: "x86_64"
  format_overrides:
  - goos: "windows"
    format: "zip"
