version: 2

jobs:
  release:
    docker:
    - image: "circleci/golang:1.12"
    steps:
    - checkout
    - run: "curl -sL https://git.io/goreleaser | bash"
  test:
    docker:
    - image: "circleci/golang:1.12"
    steps:
    - checkout
    - run: "go mod download"
    - run: "mkdir -p /tmp/artifacts"
    - run: "go test -coverprofile=c.out"
    - run: "go tool cover -html=c.out -o coverage.html"
    - run: "mv coverage.html /tmp/artifacts"
    - store_artifacts:
        path: "/tmp/artifacts"
    - run:
        name: "Upload Coverage Results"
        command: |
          bash <(curl -s https://codecov.io/bash) -f c.out  -n ${CIRCLE_BUILD_NUM} -t ${CODECOV_TOKEN} -y .codecov.yml

workflows:
  version: 2
  build_test_release:
    jobs:
    - test
    - release:
        requires:
        - "test"
        filters:
          tags:
            only: /^v.*/
          branches:
            only: "master"
